project:
  type: website
  output-dir: docs

website:
  title: "Open Source Program Office | CERTH"
  navbar:
    # background: "#cfe1ed"
    left:
      - href: index.qmd
        text: Welcome
      
    right: 
      - text: "🌐 Language"
        menu:
          - text: "English"
            href: index.qmd
          - text: "Greek"
            href: index-gr.qmd
      - icon: github
        href: https://github.com/natanast/OSPO_CERTH
        
  page-footer: 
    border: true
    right: "[License](https://github.com/natanast/OSPO_CERTH/LICENSE)"

editor: source

format:
  html:
    theme: [morph, sass/theme-light.scss]
    fig-format: svg
    toc: false

knitr:
  opts_chunk:
    dev: svg
    dev.args: { bg: "transparent" }