---
title: ""
format: html
editor: visual
---

::: {.custom-hero .column-screen}
:::

# Γραφείο Λογισμικού Ανοιχτού Κώδικα \| ΕΚΕΤΑ

Ο ανοιχτός κώδικας είναι άρρηκτα συνδεδεμένος με την ανάπτυξη σύγχρονων τεχνολογιών και αποτελεί το θεμέλιο της συντριπτικής πλειοψηφίας των βάσεων κώδικα σε όλους τους βιομηχανικούς κλάδους και τους τεχνολογικούς τομείς, όπως η Τεχνητή Νοημοσύνη (AI), η Διαχείριση Μεγάλων Δεδομένων (Big Data), η Υπολογιστική Νέφους (Cloud Computing), και η Κυβερνοασφάλεια. Σχεδόν όλοι οι οργανισμοί εξαρτώνται από τεχνολογία που δημιουργείται από την κοινότητα ανοιχτού κώδικα. Χαρακτηριστικά, το λειτουργικό σύστημα Linux και οι διάφορες διανομές του βρίσκονται πίσω από το σύνολο των υπερυπολογιστών παγκοσμίως (με βάση τη λίστα top-500), ενώ το σύνολο σχεδόν των εξελίξεων στον τομέα της Τεχνητής Νοημοσύνης βασίζεται σε δημοφιλείς πλατφόρμες ανοιχτού λογισμικού όπως η PyTorch, TensorFlow και Jupyter. Παράλληλα, το αυξανόμενο κόστος κτήσης και τεχνικής υποστήριξης των εμπορικών λύσεων και υπηρεσιών λογισμικού σε συνδυασμό με την κρισιμότητα της ψηφιακής κυριαρχίας (digital sovereignty) καθιστούν τις τεχνολογίες ανοιχτού κώδικα ως ένα θεμελιώδες συστατικό της ανεξάρτητης έρευνας και ανάπτυξης στη σημερινή εποχή.

# Ρόλος ενός Γραφείου Λογισμικού Ανοιχτού Κώδικα (OSPO)

Ένα OSPO λειτουργεί ως κεντρική διεπαφή για δραστηριότητες που σχετίζονται με τον ανοιχτό κώδικα σε όλο τον οργανισμό, συγκεντρώνοντας την απαιτούμενη τεχνογνωσία από διαφορετικές οπτικές γωνίες (όπως η νομική, η οικονομική, η τεχνική και η οπτική της κοινότητας). Το OSPO αποτελεί καθιερωμένη πρακτική σε πολλές εταιρείες (όπως η Microsoft και η Google), δημόσιους φορείς (όπως η κυβέρνηση της Γαλλίας) και διακυβερνητικούς οργανισμούς (όπως ο ΠΟΥ και το CERN ). Λειτουργεί ως το κέντρο εξειδίκευσης (center of competency) για τις λειτουργίες και τη δομή ανοιχτού κώδικα ενός οργανισμού και είναι υπεύθυνο για τον καθορισμό και την εφαρμογή στρατηγικών και πολιτικών που καθοδηγούν αυτές τις προσπάθειες.

# Δράσεις του Γραφείου Λογισμικού Ανοιχτού Κώδικα στο ΕΚΕΤΑ

Το Γραφείο Προγραμμάτων Ανοιχτού Κώδικα (OSPO) στο ΕΚΕΤΑ αποτελεί σημείο εισόδου στην τεχνογνωσία του ΕΚΕΤΑ στον Ανοιχτό Κώδικα. Το OSPO CERTH είναι μια ανοιχτή και συμπεριληπτική υπηρεσία, που λειτουργεί συνεργατικά με όλα τα Ινστιτούτα, και εξωτερικά ως μια ορατή διεπαφή για πιθανούς εταίρους και το ενδιαφερόμενο κοινό. Αυτό περιλαμβάνει εκδηλώσεις, επικοινωνία, υποστήριξη και εκπαίδευση καθ' όλη τη διάρκεια του έτους.

**Εσωτερικά**, το OSPO CERTH έχει τους εξής ρόλους:

-    Να συμβουλεύει, να καθοδηγεί και να εκπαιδεύει το προσωπικό του ΕΚΕΤΑ σχετικά με βέλτιστες πρακτικές, εργαλεία, άδειες χρήσης, εξελίξεις κ.λπ. για έργα Ανοιχτού Κώδικα.

-   Να παρέχει συστάσεις για τη διάθεση λογισμικού και υλικού που αναπτύσσεται στο ΕΚΕΤΑ ως έργο ανοιχτού κώδικα.

-   Να παρέχει κατευθυντήριες γραμμές και βέλτιστες πρακτικές για τις τεχνικές πτυχές του διαμοιρασμού κώδικα και σχεδίων, π.χ. πού να φιλοξενούνται, ποιες υπηρεσίες να χρησιμοποιούνται, κατάλληλη χρήση των υποδομών του ΕΚΕΤΑ, γενικά εργαλεία για Ανοιχτό Κώδικα όπως έλεγχοι συμμόρφωσης αδειών και τρόπος ρύθμισης δοκιμών.

-   Να διευκολύνει και να ενισχύει τη διάδοση του Ανοιχτού Κώδικα.

-   Να συμβουλεύει τη Διοίκηση του ΕΚΕΤΑ για θέματα Ανοιχτού Κώδικα με αντίκτυπο στον οργανισμό.

**Εξωτερικά**, το OSPO CERTH έχει τους εξής ρόλους:

-   Να παρέχει έναν δημόσιο κατάλογο του Ανοιχτού Κώδικα του ΕΚΕΤΑ που είναι εύκολα προσβάσιμος από τον ιστότοπο του OSPO CERTH.

-   Να καθοδηγεί τα ενδιαφερόμενα εξωτερικά μέρη σε ευκαιρίες, έργα και εμπειρογνώμονες στο EKETA μέσω του δημόσιου καταλόγου, εκδηλώσεων, εξωτερικής επικοινωνίας, ιστοτόπου, κ.λπ.

-   Να υποστηρίζει εξωτερικά ερωτήματα προς τη διοίκηση του ΕΚΕΤΑ που σχετίζονται με τον Ανοιχτό Κώδικα.
