---
title: ""
format: html
editor: visual
---

::: {.custom-hero .column-screen}
:::

# Open Source Program Office \| CERTH

Open source is inextricably linked to the development of modern technologies and constitutes the foundation of the vast majority of codebases across all industrial sectors and technological domains, such as Artificial Intelligence (AI), Big Data Management, Cloud Computing, and Cybersecurity. Almost all organizations depend on technology created by the open-source community. Characteristically, the Linux operating system and its various distributions power all of the world's supercomputers (based on the top-500 list), while nearly all advancements in the field of Artificial Intelligence rely on popular open-source software platforms such as PyTorch, TensorFlow, and Jupyter. Concurrently, the increasing acquisition and technical support costs of commercial software solutions and services, combined with the criticality of digital sovereignty, render open-source technologies a fundamental component of independent research and development in the contemporary era.

# Role of an Open Source Programs Office (OSPO)

An OSPO operates as a central interface for open-source-related activities throughout an organization, consolidating the requisite expertise from diverse perspectives (including legal, financial, technical, and community standpoints). The OSPO is an established practice in numerous corporations (such as Microsoft and Google), public entities (such as the Government of France), and intergovernmental organizations (such as the WHO and CERN). It functions as the center of competency for an organization's open-source operations and structure, and it is responsible for defining and implementing the strategies and policies that guide these endeavors.

# Activities of the Open Source Software Office at CERTH

The Open Source Programs Office (OSPO) at CERTH serves as an entry point to CERTH's open-source expertise. The CERTH OSPO is an open and inclusive service, operating collaboratively with all Institutes, and serving externally as a visible interface for potential partners and the interested public. This encompasses events, communication, support, and training throughout the year.

**Internally**, the CERTH OSPO has the following roles:

-   To advise, guide, and train CERTH staff regarding best practices, tools, licensing, developments, etc., for Open Source projects.

-   To provide recommendations for the release of software and hardware developed at CERTH as open-source projects.

-   To provide guidelines and best practices concerning the technical aspects of sharing code and designs (e.g., hosting locations, appropriate services to utilize, proper use of CERTH infrastructures, general Open Source tools such as license compliance checks, and testing configuration methodologies).

-   To facilitate and enhance the dissemination of Open Source.

-   To advise CERTH Management on Open Source matters that impact the organization.

**Externally**, the CERTH OSPO has the following roles:

-   To provide a public directory of CERTH's Open Source portfolio that is easily accessible via the CERTH OSPO website.

-   To guide interested external parties toward opportunities, projects, and experts at CERTH through the public directory, events, external communications, the website, etc.

-   To support external inquiries directed to CERTH management that pertain to Open Source.
